name: Build Pure-Data externals

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
      
  build_ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: clone Pure-Data
      run: git clone --depth=1 https://github.com/pure-data/pure-data.git
    - name: make
      run: PDDIR=pure-data make
    - name: install
      run: PDLIBDIR=package make install
    - name: Archive Package
      uses: actions/upload-artifact@v2
      with:
        name: pmpd
        path: package/pmpd
    
  build_macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: clone Pure-Data
      run: git clone --depth=1 https://github.com/pure-data/pure-data.git
    - name: make
      run: PDDIR=pure-data make
    - name: install
      run: PDLIBDIR=package make install
    - name: Archive Package
      uses: actions/upload-artifact@v2
      with:
        name: pmpd
        path: package/pmpd

  build_windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: clone Pure-Data
      run: git clone --depth=1 https://github.com/pure-data/pure-data.git
    - name: make
      run: PDDIR=pure-data make
    - name: install
      run: PDLIBDIR=package make install
    - name: Archive Package
      uses: actions/upload-artifact@v2
      with:
        name: pmpd
        path: package/pmpd
        
  package_release:
    runs-on: ubuntu-latest
    needs: [ build_ubuntu, build_macos, build_windows ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: pmpd
          path: pmpd
      - name: Rezip
        shell: bash
        run: |
          ls
          SHORT=${GITHUB_REF:11} # remove the 'refs/tags/' prefix
          SLUG=${SHORT//\//_} # replace '/' with '_'
          zip -r pmpd-${SLUG}.zip pmpd
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: pmpd*.zip